"use client";

import "~/styles/globals.css";

import { useState } from "react";
// import type { Metadata } from "next";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { FaCircleNotch, FaGoogle } from "react-icons/fa";

import { authClient } from "~/auth/client";
import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./_components/shared/SideNav";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// const geist = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { data: session } = authClient.useSession();
  return (
    <html lang="en" className="bg-background overflow-hidden text-white">
      <body>
        <TRPCReactProvider>
          <main className="flex h-screen overflow-hidden">
            {session ? (
              <AuthenticatedLayout>{children}</AuthenticatedLayout>
            ) : (
              <LoginLayout />
            )}
            <ReactQueryDevtools initialIsOpen={false} />
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const LoginLayout = () => {
  const socialProviders = [
    { label: "google", icon: <FaGoogle /> },
    // { label: "github", icon: <FaGithub /> },
  ];

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [emailError, setEmailError] = useState("");
  const [emailLoginLoading, setEmailLoginLoading] = useState(false);
  const handleEmailSignIn = async () => {
    setEmailLoginLoading(true);
    // await authClient.signUp.email({
    //   email,
    //   password,
    //   name: "your name",
    // });
    await authClient.signIn.email({
      email,
      password,
      rememberMe: true,
      fetchOptions: {
        onError: (error) => {
          setEmailError(error.error.message);
        },
        onResponse: () => {
          setEmailLoginLoading(false);
        },
      },
    });
  };

  return (
    <div className="flex h-screen w-screen flex-col items-center pt-40">
      <div className="bg-foreground flex w-2/3 flex-col items-center justify-center rounded p-8 shadow-md">
        <h3 className="text-center font-bold">Welcome to Paratus</h3>
        <p className="text-gray text-sm">
          This web application is by invitation only...
        </p>
        <div className="mt-8">
          {socialProviders.map((provider) => (
            <button
              key={provider.label}
              className="mb-4 flex w-full items-center justify-center gap-2 rounded border bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
              onClick={() =>
                authClient.signIn.social({ provider: provider.label })
              }
            >
              {provider.icon}
              {provider.label.charAt(0).toUpperCase() + provider.label.slice(1)}
            </button>
          ))}
        </div>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            void handleEmailSignIn();
          }}
          className="w-full"
        >
          {emailError && <p className="text-danger">{emailError}</p>}

          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Email address"
            className="mt-4 w-full rounded border bg-transparent px-4 py-2 text-white outline-none"
          />
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password"
            className="mt-4 w-full rounded border bg-transparent px-4 py-2 text-white outline-none"
          />
          <button
            type="submit"
            className="mt-4 flex w-full items-center justify-center gap-4 rounded border bg-green-600 px-4 py-2 text-white hover:bg-green-700"
          >
            {emailLoginLoading && <FaCircleNotch className="animate-spin" />}
            Sign in with Email
          </button>
        </form>
      </div>
    </div>
  );
};

const AuthenticatedLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <>
      <SideNav />
      <div className="flex flex-1 overflow-hidden">{children}</div>
    </>
  );
};
