import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./_components/shared/SideNav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} bg-background overflow-hidden text-white`}
    >
      <body>
        <TRPCReactProvider>
          <main className="flex h-screen overflow-hidden">
            <SideNav />
            <div className="flex flex-1 overflow-hidden">{children}</div>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
